name: Deploy Full Stack Application to EC2 # ワークフロー名

on:
  push:
    branches:
      - main # mainブランチへのプッシュ時に実行

jobs:
  deploy:
    runs-on: ubuntu-latest # GitHub ActionsのVMはUbuntu最新版を使用

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # リポジトリのコードをVMにチェックアウト

      - name: Set up SSH key # EC2インスタンスへのSSH接続に必要な秘密鍵を設定
        run: |
          mkdir -p ~/.ssh # .sshディレクトリが存在しない場合は作成
          echo "${{ secrets.EC2_KEY_B64 }}" | base64 -d > ~/.ssh/id_rsa # Base64デコードされた秘密鍵をファイルに保存
          chmod 600 ~/.ssh/id_rsa # 秘密鍵のパーミッションを設定 (必須)
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts # SSHホストのフィンガープリントをknown_hostsに追加 (セキュリティ強化)

      - name: Deploy and Build on EC2 via SSH # ★デプロイとビルドをSSH経由でEC2上で実行
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user/rehab-app/rehab-management-system

            git pull origin main

            echo "Building frontend on EC2..."
            cd frontend 
            npm install 
            npm run build 
            cd .. 

            docker-compose down

            docker-compose build --no-cache 

            docker-compose up -d

            echo "Reloading Nginx on EC2..."
            sudo systemctl reload nginx 
          EOF
